/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shell;

import RMIInterface.RMIInterface;
import com.wwecuador.voduc.gui.VentanaReproductor;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jahyr
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    public static Scanner ingresoTexto = new Scanner (System.in);
    public static Scanner ingresoEntero = new Scanner (System.in);
    
    private static String serverAddress = "192.168.1.101";
    private static int serverPort = 3232;
    
    private boolean info = true;
    
    Registry registry;
    private static RMIInterface servidorObj;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        try {
            registry = LocateRegistry.getRegistry(serverAddress, serverPort);
            servidorObj = (RMIInterface) registry.lookup("operacionservidor");
            textoListaPeliculas.setText(servidorObj.imprimirLista());
        } catch (RemoteException ex) {
            ex.printStackTrace();
        } catch (NotBoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelTituloBienvenida = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoListaPeliculas = new javax.swing.JTextArea();
        infoRadioButton = new javax.swing.JRadioButton();
        playRadioButton = new javax.swing.JRadioButton();
        textoCodigo = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VODUC");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(100, 100, 600, 400));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        labelLogo.setBackground(new java.awt.Color(0, 0, 0));
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        labelTituloBienvenida.setBackground(new java.awt.Color(0, 0, 0));
        labelTituloBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTituloBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloBienvenida.setText("VODUC");

        jScrollPane2.setBorder(null);

        textoListaPeliculas.setEditable(false);
        textoListaPeliculas.setBackground(new java.awt.Color(0, 0, 0));
        textoListaPeliculas.setColumns(20);
        textoListaPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        textoListaPeliculas.setRows(5);
        textoListaPeliculas.setBorder(null);
        textoListaPeliculas.setFocusable(false);
        textoListaPeliculas.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(textoListaPeliculas);

        infoRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        infoRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        infoRadioButton.setSelected(true);
        infoRadioButton.setText("Información");
        infoRadioButton.setBorder(null);
        infoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoRadioButtonActionPerformed(evt);
            }
        });

        playRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        playRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        playRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        playRadioButton.setText("Reproducir");
        playRadioButton.setBorder(null);
        playRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playRadioButtonActionPerformed(evt);
            }
        });

        textoCodigo.setText("Código");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(infoRadioButton)
                        .addGap(33, 33, 33)
                        .addComponent(playRadioButton)
                        .addGap(27, 27, 27)
                        .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTituloBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelTituloBienvenida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoRadioButtonActionPerformed
        // TODO add your handling code here:
        infoRadioButton.setSelected(true);
        playRadioButton.setSelected(false);
        info = true;
    }//GEN-LAST:event_infoRadioButtonActionPerformed

    private void playRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playRadioButtonActionPerformed
        // TODO add your handling code here:
        infoRadioButton.setSelected(false);
        playRadioButton.setSelected(true);
        info = false;
    }//GEN-LAST:event_playRadioButtonActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        if (info){
            informacionDePelicula();
        } else {
            reproducirPelicula();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    public void informacionDePelicula(){
        if (!textoCodigo.equals("Código") && !textoCodigo.equals("")){
            String codigo = textoCodigo.getText();
            String[] codigos = codigo.split("-");
            try {
                servidorObj = (RMIInterface) (registry.lookup("operacionservidor"));
                String infoPeli = servidorObj.solicitarInfoPelicula(codigos[0], codigos[1]);
                if(infoPeli.equals("Código incorrecto.")){
                    System.err.println("Error: Código incorrecto.");
                } else {
                    System.out.println(infoPeli);
                }
            } catch (RemoteException ex) {
                ex.printStackTrace();
            } catch (NotBoundException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void reproducirPelicula() {
        if (!textoCodigo.equals("Código") && !textoCodigo.equals("")){
            String codigo = textoCodigo.getText();
            String[] codigos = codigo.split("-");
            try {
                servidorObj = (RMIInterface) (registry.lookup("operacionservidor"));
                String args[] = new String[2];
                args[0] = servidorObj.play(codigos[0], codigos[1]);
                if(args[0].equals("Código incorrecto.")){
                    System.err.println("Error: Código incorrecto.");
                } else {
                    args[1] = "<html><b>"+servidorObj.getTitulo(codigos[0], codigos[1]).replace(" ", "-")+"</b></html>";

                    try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Nimbus".equals(info.getName())) {
                                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                break;
                            }
                        }
                    } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(VentanaReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(VentanaReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(VentanaReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(VentanaReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>
                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new VentanaReproductor(args).setVisible(true);
                        }
                    });
                }
            } catch (RemoteException ex) {
                ex.printStackTrace();
            } catch (NotBoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JRadioButton infoRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelTituloBienvenida;
    private javax.swing.JRadioButton playRadioButton;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextArea textoListaPeliculas;
    // End of variables declaration//GEN-END:variables
}
